Feature/template integration
arqamtahir/Food-ordering-system pull request #1
Opened 2022-08-24 10:47 UTC by arqamtahir

2022-08-24 10:50 UTC, MShahnoor commented
Farigh he

2022-08-24 10:52 UTC, hamza5999 commented
better luck next time

2022-08-30 09:55 UTC, moizafzal936 requested changes

2022-08-30 09:55 UTC, moizafzal936 commented on app/assets/stylesheets/application.scss
>   *= require_self
Change commit name

2022-08-30 09:55 UTC, moizafzal936 commented on app/javascript/packs/application.js
> +window.$ = window.jQuery = require("jquery");
Add different commit for jquery.

2022-08-30 09:55 UTC, moizafzal936 commented on config/webpacker.yml
> +  additional_paths: ["vendor/assets/javascripts/dashboard"]
Change commit name

2022-08-30 09:55 UTC, moizafzal936 commented on app/javascript/packs/application.js
> +
Change the commit name

2022-08-30 09:55 UTC, moizafzal936 commented on app/assets/stylesheets/home.scss
> +// Place all the styles related to the home controller here.
Additional file!

2022-08-30 09:55 UTC, moizafzal936 commented on app/helpers/home_helper.rb
> +module HomeHelper
Additional File!

2022-08-30 09:55 UTC, moizafzal936 commented on test/controllers/home_controller_test.rb
> +require "test_helper"
Additional File

2022-08-30 09:55 UTC, moizafzal936 commented on config/routes.rb
>  Rails.application.routes.draw do
Not relevant to commit.

2022-08-30 09:55 UTC, moizafzal936 commented on app/views/dashboard/_content-section.html.erb
> +                        <%= render 'dashboard/stats/chart' %>
Indentation need to be fixed

2022-08-31 07:51 UTC, closed without merging